#define PRIMARY_COLOR {0.96,0.65,0.12,0.8}
#define COLOR_PRIMARY(ALPHA) {0.96,0.65,0.12,ALPHA}
#define DARK_COLOR {0.12,0.14,0.16,0.8}
#define COLOR_DARK(ALPHA) {0.12,0.14,0.16,ALPHA}
#define BRIGHT_COLOR {1,1,1,0.8}
#define COLOR_BRIGHT(ALPHA) {1,1,1,ALPHA}
#define WHITE_SHADOW {1,1,1,0.1}
#define COLOR_BLACK(ALPHA) {0,0,0,ALPHA}
#define DISABLED_COLOR {0.52,0.54,0.56,1}
#define DISABLED_SETTING \
	colorDisabled[] = DISABLED_COLOR;\
	colorBackgroundDisabled[] = DARK_COLOR

#define SIDEBAR_WIDTH safeZoneW * 0.2
#define SIDEBAR_BORDER safeZoneW * 0.0025
#define SIDEBAR_CONTENT_WIDTH (SIDEBAR_WIDTH - 2 * SIDEBAR_BORDER)
#define SIDEBAR_ITEM_HEIGHT safeZoneH * 0.045

#define LOADOUT_WIDTH safeZoneW * 0.45
#define LOADOUT_HEIGHT safeZoneH * 0.66

#define LOADOUT_GUTTER SIDEBAR_BORDER

#define LOADOUT_L_COL_WIDTH safeZoneW * 0.175
#define LOADOUT_R_COL_WIDTH (LOADOUT_WIDTH - LOADOUT_L_COL_WIDTH)
#define LOADOUT_HEADER_HEIGHT safeZoneH * 0.04

#define LOADOUT_SMALL_HEADER_HEIGHT LOADOUT_HEADER_HEIGHT / 2
#define LOADOUT_WEAPON_PICTURE_HEIGHT LOADOUT_L_COL_WIDTH * 9 / 16
#define LOADOUT_WEAPON_DESC_HEIGHT LOADOUT_WEAPON_PICTURE_HEIGHT / 3
#define LOADOUT_WEAPON_FRAME_HEIGHT (LOADOUT_SMALL_HEADER_HEIGHT + LOADOUT_WEAPON_PICTURE_HEIGHT + LOADOUT_WEAPON_DESC_HEIGHT)

#define LOADOUT_PERK_WIDTH (LOADOUT_L_COL_WIDTH - LOADOUT_GUTTER) / 2
#define LOADOUT_PERK_PICTURE_SIZE LOADOUT_PERK_WIDTH * 0.66
