#define CLASS_CUSTOMIZE_WIDTH safeZoneW * 0.66
#define CLASS_CUSTOMIZE_HEIGHT safeZoneH * 0.45
#define CLASS_CUSTOMIZE_COL_WIDTH CLASS_CUSTOMIZE_WIDTH / 2
#define CLASS_CUSTOMIZE_HEADER_HEIGHT safeZoneH * 0.04
